spring.application.name=backend-service
server.port=8081
app.upload.dir=${user.home}/multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Spring Cloud ZooKeeper Discovery: registers at /services/${spring.application.name}/<id>
spring.cloud.zookeeper.connect-string=localhost:2181
spring.cloud.zookeeper.discovery.instance-host=localhost
